apiVersion: servicecatalog.k8s.io/v1beta1
kind: ClusterServiceBroker
metadata:
  name: cloud-broker
spec:
  authInfo:
    basic:
      secretRef:
        name: broker-auth
        namespace: default
  # Points to the endpoint of a service broker. (This example is not a working URL.)
  url:  http://csb.default.svc.cluster.local:8080