secretGenerator:
- name: mysql-secrets
  literals:
  - rootpassword=AG00dS3cr3t!
  - dbpassword=Ah0th3rG00dS3cr3t!
  - dbuser=dbuser
- name: broker-secrets
  literals:
  - username=csb-broker
  - userpassword=S0m3S3cr3tPa$$w0rd
- name: broker-auth
  literals:
  - username=csb-broker
  - password=S0m3S3cr3tPa$$w0rd
configMapGenerator:
- name: broker-config
  files:
  - ./config-files/broker-config.yaml
resources:
- mysql-deployment.yml
- csb-deployment.yml
- clusterbroker.yml